import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Listage from "../components/Listage";
// import Image from 'next/image'
// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Book Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Listage />

      <main></main>
    </div>
  );
};

export default Home;
